name = "entradas-qr-condesa"
account_id = "176a9c9035080982cee7a55ce32ef1ec"
main = "workers/api/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "entradas-qr-db"
database_id = "1884e331-876c-4e12-9271-739474c41814"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "entradas-qr-assets"

[vars]
QR_BASE_URL = "https://condesamansion.com.ar"